/*
 * This file is automatically generated by Config Tools.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

public static class gameConfEnums
{
	public static readonly string[] fileNames = {
		"iconConf",
		"wordConf",
		"levelConf",
	};
}

public enum gameConfEnumsFileEnum
{
	iconConf,
	wordConf,
	levelConf,
}


